AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: go1.x
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: 'xxxxxx-bucket'