Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Handler: index.handler
      ImageConfig: 
        Command:
          - app.hello_world
      Architectures:
        - fake
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: hello_world-v1