AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  MySampleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      AutoPublishAlias: String
      Definition:
        StartAt: MyLambdaState
        States:
          MyLambdaState:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:123456123456:function:my-sample-lambda-app
            ResultPath: '$.Result'
            End: true
      DefinitionSubstitutions: Map
      DefinitionUri: String | S3Location
      DeploymentPreference: DeploymentPreference
      Events: 
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /group/{user}
            RestApiId: 
              Ref: MyApi
      Logging: LoggingConfiguration
      Name: String
      PermissionsBoundary: String
      Policies: String | List | Map
      PropagateTags: Boolean
      RolePath: String
      Role: String
      Tags: Map
      Tracing: TracingConfiguration
      # Type: String