AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BaseRubyGemsLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    # Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: baseRubyGems
      ContentUri: ../layer
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - ruby2.5