AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ESB PackingList API

Resources:
  XyZFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: somefunction
      Handler: lambda.handler
      Runtime: python3.6
      CodeUri: ...
      Events:
        MyEvent:
          Type: Api
          Properties:
            Path: /mypath
            Method: get
# lines starting here...
          security:
            api_key:
              type: "apiKey"
              name: "x-api-key"
              in: "header"
