Parameters:
  IsListening:
    AllowedValues: [true, false]
    Default: true
    Type: String

Conditions:
  EventsActive: !Equals ['true', !Ref IsListening]

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ExampleTopic:
          Type: SNS
          Condition: EventsActive